Добавил контроллеры для User и Film
Programmer112P/java-filmorate pull request #3
Opened 2023-03-05 19:26 UTC by Programmer112P

2023-03-05 19:39 UTC, Programmer112P commented
Я не добавлял Unit-тестирование, потому что у нас нет совсем никакой бизнес-логики
А все тесты, которые нам давали в Postman, прошли успешно

2023-03-06 17:34 UTC, YazykovMikhail commented
Тесты обавить все таки стоит. В задании написано:
Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.

приведу пример как может выглядить тестирование Film, другое сделаешь сам:

class FilmControllerTest {

	static FilmController filmController = new FilmController();

	@Test
	void validateFilmOk() {
		final Film validFilm = new Film();
		validFilm.setName("Film Name");
		validFilm.setDescription("Film description");
		validFilm.setReleaseDate(LocalDate.now());
		validFilm.setDuration(100);
		filmController.validate(validFilm);
	}

	@Test
	void validateFilmFail() {
		final Film film = new Film();
		Exception exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film name invalid", exception.getMessage());

		film.setName("");
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film name invalid", exception.getMessage());

		film.setName("film Name");
		film.setDescription("f".repeat(201));
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film description invalid", exception.getMessage());

		film.setDescription("Film description");
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film release date invalid", exception.getMessage());

		film.setReleaseDate(LocalDate.MIN);
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film release date invalid", exception.getMessage());

		film.setReleaseDate(LocalDate.now());
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film duration invalid", exception.getMessage());

		film.setDuration(-10);
		exception = assertThrows(ValidationException.class, () -> filmController.validate(film));
		assertEquals("Film duration invalid", exception.getMessage());
	}


так выглядит метод валидации:
void validate(User data) {
		if (data.getLogin() == null || data.getLogin().isEmpty() || data.getLogin().contains(" ")) {
			throw new ValidationException("User login invalid");
		}
		if (data.getEmail() == null || data.getEmail().isEmpty() || !data.getEmail().contains("@")) {
			throw new ValidationException("User email invalid");
		}
		if (data.getName() == null || data.getName().isEmpty()) {
			data.setName(data.getLogin());
		}
		if (data.getBirthday() != null && data.getBirthday().isAfter(LocalDate.now())) {
			throw new ValidationException("User birthday invalid");
		}
	}
	
	только лучше вынеси его из контроллера в тестыи вызывай от туда. 
	
	Пока более сложные тесты вы не прошли, можно всользоваться такой хитростью.

2023-03-06 18:08 UTC, YazykovMikhail requested changes
В целом не плохр, молодец, но есть что поправить.

2023-03-06 18:08 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmReleaseDateValidator.java
> +        return true;
дата релиза — не раньше 28 декабря 1895 года;
т.е null nоже не может быть.

Используй тогда над датой еще аннотацию @NotNull

2023-03-06 18:08 UTC, YazykovMikhail commented on src/main/resources/ValidationMessages.properties
> +releaseDate.invalid=The date is invalid
прописывай ссообщение прям в классе, не нужно через проперти

2023-03-10 12:15 UTC, Programmer112P commented
Моя попытка изучить MVC-архитектуру, появилось пару вопросов:
Я каждый контроллер положил соответствующий service объект - так и должно быть?
Не нужна для этого общая модель со всеми сервисами внутри?

И ещё вопрос по тому, какой ответ наш API должен давать на сервер
В случае если мы вызываем create или apdate запрос, возвращается единичный объект
Если getAll - возвращается массив объектов
При ошибке вообще приходит 400 или 500
Как должно быть по-хорошему? Насколько я понял такой подход не очень удобен
Можно было бы всегда возвращать лист всегда например, а не единичный объект, и возвращать 400/500 тоже плохо

Ещё я сделал защиту ветки, так что надо будет поставить approve, если все ок

2023-03-10 12:33 UTC, YazykovMikhail approved these changes
Успехов дальше ;)

2023-03-10 12:33 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Список фильмов получен в контроллере");
какой список? а вдруг не получен и там null?
log.info("/films  запрос getAll");
Переменная = service.getAll()
log.info("/films  getAll ответ: {}", Переменная);
return Переменная

2023-03-10 13:09 UTC, Programmer112P commented
Не могу смержить все ещё, не знаю в чем дело

2023-03-10 13:40 UTC, merged